// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shop.web;

#nullable disable

namespace shop.web.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241201233622_AddTablesTableBillAndTable")]
    partial class AddTablesTableBillAndTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("shop.web.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Thumb")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("shop.web.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountPaied")
                        .HasColumnType("int");

                    b.Property<int>("TableBillId")
                        .HasColumnType("int");

                    b.Property<int>("TypePayment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableBillId");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("shop.web.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReservedTo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TableBillId")
                        .HasColumnType("int");

                    b.Property<int>("TableStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableBillId");

                    b.ToTable("tables");
                });

            modelBuilder.Entity("shop.web.Entities.TableBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateClosing")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOpen")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiscountAmount")
                        .HasColumnType("int");

                    b.Property<int>("PaiedAmount")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tableBills");
                });

            modelBuilder.Entity("shop.web.Entities.PaymentMethod", b =>
                {
                    b.HasOne("shop.web.Entities.TableBill", "TableBill")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("TableBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableBill");
                });

            modelBuilder.Entity("shop.web.Entities.Table", b =>
                {
                    b.HasOne("shop.web.Entities.TableBill", null)
                        .WithMany("Tables")
                        .HasForeignKey("TableBillId");
                });

            modelBuilder.Entity("shop.web.Entities.TableBill", b =>
                {
                    b.Navigation("PaymentMethods");

                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
